---
output:
  html_document: default

title: "SubsidyExplorer - Step 6: Main Results"
author: "Kat Millage, Vienna Saccomanno, Laura Lea Rubino, Christopher Costello"
date: "`r format(Sys.time(), '%B %d, %Y')`"
fontsize: 11pt
bibliography: "../pew-subsidies.bib"
---

# Introduction 

This script generates the most ambitious global and regional results obtained by removing all capacity enhancing subsidies from all WTO Members and Observers.

```{r setup, include=FALSE}
# Load packages
library(knitr) 
library(tidyverse)

knitr::opts_chunk$set(echo = TRUE)

make_plots <- T

if(make_plots){
  library(RColorBrewer)
  library(scales)
}

# Directories for the output files generated by this script
results_dir <- here::here("results", "06-main-results/")
if (dir.exists(results_dir) == F) {
  dir.create(results_dir, recursive = T)
}
```

```{r}
# Source model script
source(here::here("app", "scripts", "BioEconModel.R"))

# Source plotting script
source(here::here("scripts", "functions", "BioEconomicModelPlots.R"))
```

```{r}
# Load vessel list
vessel_dat <- read.csv(here::here("app", "data", "vessel_list_2018_final.csv"), stringsAsFactors = F)

# Create high seas code
vessel_dat <- vessel_dat %>%
  mutate(eez_hs_code = case_when(eez_id == 0 ~ paste0("HS-", fao_region),
                                 TRUE ~ as.character(eez_id)))

# Load country dependencies helper file
country_dependencies <- read_csv(here::here("data", "lookup-tables", "country_dependencies.csv"))
```

```{r}
# Load biological parameters for the model
bio_dat_regional <- read.csv(here::here("app", "data", "model_parameters_regional_3_regions.csv"))

# Regional parameter list
bio_dat_regional_list <- bio_dat_regional %>%
  gather(region, value, -c(1:2)) %>%
  group_by(region) %>%
  group_split()
```

```{r}
# Threshold to be considered managed (using FMI scores)
managed_cutoff <- 0.66
```

## Relative subsidy effects

```{r}
# Vessel list with "effective" subsidies
rel <- read_csv(here::here("data", "lookup-tables", "oecd_relative_effects_lookup_table.csv"))

bad_subsidy_types <- c("B1", "B2", "B3", "B4", "B5", "B6", "B7")
ugly_subsidy_types <- c("C1", "C2", "C3")

vessel_dat_relative <- vessel_dat %>%
   mutate(B1_subs = B1_subs * rel$rel_effect_effort[rel$type == "B1"], 
           B2_subs = B2_subs * rel$rel_effect_effort[rel$type == "B2"],
           B3_subs = B3_subs * rel$rel_effect_effort[rel$type == "B3"],
           B4_subs = B4_subs * rel$rel_effect_effort[rel$type == "B4"],
           B5_subs = B5_subs * rel$rel_effect_effort[rel$type == "B5"], 
           B6_subs = B6_subs * rel$rel_effect_effort[rel$type == "B6"],
           B7_subs = B7_subs * rel$rel_effect_effort[rel$type == "B7"], 
           C1_subs = C1_subs * rel$rel_effect_effort[rel$type == "C1"], 
           C2_subs = C2_subs * rel$rel_effect_effort[rel$type == "C2"],
           C3_subs = C3_subs * rel$rel_effect_effort[rel$type == "C3"], 
           bad_subs = rowSums(select(., one_of(paste0(bad_subsidy_types, "_subs")))),
           ugly_subs = rowSums(select(., one_of(paste0(ugly_subsidy_types, "_subs")))))
```

```{r pressure, echo=FALSE}
# Assign fleets to vessels
global_fleet_rel_vessels <- vessel_dat_relative %>%
  left_join(country_dependencies %>% dplyr::select(iso3, is_WTO), by = c("flag_iso3" = "iso3")) %>%
  mutate(fleet = case_when(is_WTO & fmi_best >= managed_cutoff & bad_subs > 0 ~ "affected_managed",
                           is_WTO & fmi_best < managed_cutoff & bad_subs > 0 ~ "affected_oa",
                           (!is_WTO & fmi_best >= managed_cutoff) ~ "unaffected_managed",
                           (!is_WTO & fmi_best < managed_cutoff) ~ "unaffected_oa",
                           TRUE ~ "unaffected_oa"))
```

```{r}
# Create model input for removing all bad subsidies
global_all_BC_rel_summary <- global_fleet_rel_vessels %>%
  group_by(region, fleet) %>%
  summarize(catch = sum(catch, na.rm = T),
            bad_subs = sum(bad_subs, na.rm = T) + sum(ugly_subs, na.rm = T),
            fishing_KWh = sum(fishing_KWh_eez_fao_ter, na.rm = T),
            removed_subs = sum(bad_subs, na.rm = T) + sum(ugly_subs, na.rm = T)) %>%
  ungroup()

# Turn into a list
global_all_BC_rel_list <- global_all_BC_rel_summary %>%
  group_by(region) %>%
  group_split()
names(global_all_BC_rel_list) <- colnames(bio_dat_regional)[-c(1:2)]

# Run model
global_all_BC_rel_results <- pmap_df(list(fleet = global_all_BC_rel_list, 
                                       region = names(global_all_BC_rel_list),
                                       bio_param = bio_dat_regional_list),
                                  BioEconModel,
                                  end_year = 2100,
                                  return = "all")

# Extract results timeseries
global_all_BC_rel_results_all <- global_all_BC_rel_results %>%
  dplyr::filter(Year > 2018) %>%
  group_by(Year, Variable, Fleet) %>%
  mutate(Diff = case_when(BAU != 0 ~ (Reform - BAU)/abs(BAU),
                          TRUE ~ 0)) %>%
  ungroup() %>%
  mutate(run_id = "rel_subs_all_bad",
         run_name = "Complete removal of capacity-enhancing subisidies - relative subsidies")

write_csv(global_all_BC_rel_results_all, paste0(results_dir, "rel_subs_all_BC_ts.csv"))
```

```{r}
# Make plots
if(make_plots){
  
  # 1) global (aggregated) timeseries plot
  global_rel_all_BC_ts_plot <- BioEconomicModelPlots(dat = global_all_BC_rel_results_all,
                                                      spatial_res = "global",
                                                      temporal_res = "all",
                                                      start_year = 2018,
                                                      end_year = 2100,
                                                      plot_name = "global_rel_subs_all_BC_ts_plot",
                                                      plot_width = 8,
                                                      plot_height = 6.5,
                                                      results_dir = results_dir)
  
  # 2) global (aggregated) "kobe" final year plot
  global_rel_all_BC_end_plot <- BioEconomicModelPlots(dat = global_all_BC_rel_results_all,
                                                      spatial_res = "global",
                                                      temporal_res = "last",
                                                      end_year = 2100,
                                                      plot_name = "global_rel_subs_all_BC_end_plot",
                                                      plot_width = 8,
                                                      plot_height = 6.5,
                                                      results_dir = results_dir)
  
  # 3) regional timeseries plot
  regional_rel_all_BC_ts_plot <- BioEconomicModelPlots(dat = global_all_BC_rel_results_all,
                                                      spatial_res = "regional",
                                                      temporal_res = "all",
                                                      start_year = 2018,
                                                      end_year = 2100,
                                                      plot_name = "regional_rel_subs_all_BC_ts_plot",
                                                      plot_width = 8,
                                                      plot_height = 6.5,
                                                      results_dir = results_dir)
  
  # 4) regional "kobe" final year plot
  regional_rel_all_BC_end_plot <- BioEconomicModelPlots(dat = global_all_BC_rel_results_all,
                                                      spatial_res = "regional",
                                                      temporal_res = "last",
                                                      end_year = 2100,
                                                      plot_name = "regional_rel_subs_all_BC_end_plot",
                                                      plot_width = 8,
                                                      plot_height = 6.5,
                                                      results_dir = results_dir)
}
```

