---
output:
  html_document: default

title: "SubsidyExplorer - Step 6: Run Model"
author: "Kat Millage, Vienna Saccomanno, Laura Lea Rubino, Christopher Costello"
date: "`r format(Sys.time(), '%B %d, %Y')`"
fontsize: 11pt
bibliography: "../pew-subsidies.bib"
---

```{r setup, include=FALSE}
# Load packages
library(knitr) 
library(tidyverse)

knitr::opts_chunk$set(echo = TRUE)

make_plots <- T

if(make_plots){
  library(RColorBrewer)
  library(scales)
}

# Directories for the output files generated by this script
results_dir <- here::here("results", "06-run-model/")
if (dir.exists(results_dir) == F) {
  dir.create(results_dir, recursive = T)
}
```

# Introduction 

This script generates the most ambitious global and regional results obtained by removing all capacity enhancing subsidies from all WTO Members and Observers.

```{r}
# Source model script
source(here::here("app", "scripts", "BioEconModel.R"))
```

```{r}
# Load vessel list
pro_rate_subsidies <- F

vessel_dat <- read.csv(here::here("app", "data", "vessel_list_2018_final.csv"), stringsAsFactors = F)

### Not applicable currently - old experimentation with pro-rating the dollar value of different subsidies
# if(pro_rate_subsidies == T){
# 
#   vessel_dat <- vessel_dat %>%
#     mutate(B1_subs = B1_subs * 0.54, # boat construction/renovation - matched to payments based on vessels
#            B2_subs = B2_subs * 1, # fishery development projects/support services - matched to payments based on variable use
#            B3_subs = B3_subs * 0.87, # port construction and renovation - matched to payments based on vessels
#            B4_subs = B4_subs * 0.87, # price/marketing support, processing infrastructure - matched to payments based on output
#            B5_subs = B5_subs * 0.76, # non-fuel tax exemptions - matched to payments based on fishers income
#            B6_subs = B6_subs * 0.56, # foreign access agreements - matched to payments based on fishers own capital
#            B7_subs = B7_subs * 0.84, # fuel - matched to payments based on fuel use
#            bad_subs = (B1_subs + B2_subs + B3_subs + B4_subs + B5_subs + B6_subs + B7_subs))
# 
# }

vessel_dat <- vessel_dat %>%
  mutate(eez_hs_code = case_when(eez_id == 0 ~ paste0("HS-", fao_region),
                                 TRUE ~ as.character(eez_id)))

# Load country dependencies helper file
country_dependencies <- read_csv(here::here("data", "lookup-tables", "country_dependencies.csv")) %>%
  mutate(territory_is_WTO = case_when(WTO_status %in% c("Member", "Observer") ~ T,
                            TRUE ~ F))

sovereign_statuses <- country_dependencies %>%
  distinct(sovereign_iso3, WTO_status) %>%
  mutate(sovereign_is_WTO = case_when(WTO_status %in% c("Member", "Observer") ~ T,
                            TRUE ~ F))

wto_lookup <- country_dependencies %>%
  left_join(sovereign_statuses, by = c("sovereign_iso3", "WTO_status")) %>%
  mutate(is_WTO = case_when(territory_is_WTO ~ T,
                            sovereign_is_WTO ~ T,
                            TRUE ~ F)) %>%
  dplyr::select(iso3, is_WTO)
```

```{r}
# Load biological parameters for the model
bio_dat_regional <- read.csv(here::here("app", "data", "model_parameters_regional_3_regions.csv"))

# Regional parameter list
bio_dat_regional_list <- bio_dat_regional %>%
  gather(region, value, -c(1:2)) %>%
  group_by(region) %>%
  group_split()
```

```{r}
# Threshold to be considered managed (using FMI scores)
managed_cutoff <- 0.66
```

## Create global fleet

```{r pressure, echo=FALSE}
# Assign fleets to vessels
global_fleet_vessels <- vessel_dat %>%
  left_join(wto_lookup, by = c("flag_iso3" = "iso3")) %>%
  mutate(fleet = case_when(is_WTO & fmi_best >= managed_cutoff & bad_subs > 0 ~ "affected_managed",
                           is_WTO & fmi_best < managed_cutoff & bad_subs > 0 ~ "affected_oa",
                           (!is_WTO & fmi_best >= managed_cutoff) ~ "unaffected_managed",
                           (!is_WTO & fmi_best < managed_cutoff) ~ "unaffected_oa",
                           TRUE ~ "unaffected_oa"))
```

## Run Model (Remove all bad subsidies)

```{r}
# Create model input for removing all bad subsidies
global_all_bad_summary <- global_fleet_vessels %>%
  group_by(region, fleet) %>%
  summarize(catch = sum(catch, na.rm = T),
            bad_subs = sum(bad_subs, na.rm = T),
            fishing_KWh = sum(fishing_KWh_eez_fao_ter, na.rm = T),
            removed_subs = sum(bad_subs, na.rm = T)) %>%
  ungroup()

# Turn into a list
global_all_bad_list <- global_all_bad_summary %>%
  group_by(region) %>%
  group_split()
names(global_all_bad_list) <- colnames(bio_dat_regional)[-c(1:2)]

# Run model
global_all_bad_results <- pmap_df(list(fleet = global_all_bad_list, 
                                       region = names(global_all_bad_list),
                                       bio_param = bio_dat_regional_list),
                                  BioEconModel,
                                  end_year = 2100,
                                  return = "all")

# Extract results timeseries
global_all_bad_results_full <- global_all_bad_results %>%
  dplyr::filter(Year > 2018) %>%
  dplyr::filter(Variable %in% c("biomass", "catches_total", "revenue_total")) %>%
  group_by(Year, Variable, Fleet) %>%
  mutate(Diff = case_when(BAU != 0 ~ (Reform - BAU)/abs(BAU),
                          TRUE ~ 0),
         BAU_global = sum(BAU, na.rm = T),
         Reform_global = sum(Reform, na.rm = T),
         Diff_global = case_when(BAU_global != 0 ~ (Reform_global - BAU_global)/abs(BAU_global),
                                 TRUE ~ 0)) %>%
  ungroup() %>%
  mutate(run_number = "A",
         run_name = "Most ambitious scenario",
         id = "A",
         Description = "Complete removal of all capacity-enhancing subsidies (for comparison)")

# Extract ending results (difference only)
global_all_bad_results_last <- global_all_bad_results_full %>%
  dplyr::filter(Year == 2100) %>%
  group_by(Year, Variable) %>%
  summarize(Value = unique(Diff_global)*100) %>%
  ungroup() %>%
  spread(Variable, Value) %>%
  rename(Biomass = biomass,
         Catches = catches_total,
         Revenue = revenue_total) %>%
  mutate(run_number = "A",
         run_name = "Most ambitious scenario")

```

```{r}
# Make plots
if(make_plots){
  
  # 1) global (aggregated) timeseries plot
  global_all_bad_plot <- global_all_bad_results_full %>%
        group_by(run_number, run_name, id, Year, Variable, Fleet) %>%
        summarize(BAU = unique(BAU_global),
                  Reform = unique(Reform_global),
                  Diff = unique(Diff_global)) %>%
        ungroup() %>%
        mutate(Variable = case_when(Variable == "biomass" ~ "Biomass",
                                    Variable == "catches_total" ~ "Catches",
                                    Variable == "revenue_total" ~ "Revenue")) %>%
        mutate(Region = "Global") %>%
        ggplot()+
        aes(x = Year, y = Diff*100, color = Variable)+
        geom_line(size = 1)+
        theme_bw()+
        geom_hline(yintercept = 0)+
        scale_x_continuous(expand = c(0,0))+
        labs(x = "Year", y = "Change relative to BAU (%)")+
        theme(legend.position = "none")+
        facet_wrap(~Variable, ncol = 1, scales = "free_y")
  
  ggsave(paste0(results_dir, "global_all_bad_timeseries_plot.png"), global_all_bad_plot, width = 7.5, height = 6, units = "in")
  
  # 2) regional timeseries plot
  regional_all_bad_plot <- global_all_bad_results_full %>%
        dplyr::select(run_number, run_name, id, Year, Variable, Fleet, Region, BAU, Reform, Diff) %>%
        mutate(Region = case_when(Region == "atlantic" ~ "Atlantic Ocean",
                                  Region == "indian" ~ "Indian Ocean",
                                  Region == "pacific" ~ "Pacific Ocean")) %>%
        mutate(Variable = case_when(Variable == "biomass" ~ "Biomass",
                                    Variable == "catches_total" ~ "Catches",
                                    Variable == "revenue_total" ~ "Revenue")) %>%
        ggplot()+
        aes(x = Year, y = Diff*100, color = Variable)+
        geom_line(size = 1)+
        theme_bw()+
        geom_hline(yintercept = 0)+
        scale_x_continuous(expand = c(0,0))+
        labs(x = "Year", y = "Change relative to BAU (%)")+
        theme(legend.position = "none")+
        facet_wrap(Variable ~ Region, ncol = 3, scales = "free_y")
  
  ggsave(paste0(results_dir, "regional_all_bad_timeseries_plot.png"), regional_all_bad_plot, width = 7.5, height = 6, units = "in")
  
  
}
```

