---
output:
  html_document: default

title: "SubsidyExplorer - Step 6: Run Model"
author: "Kat Millage, Vienna Saccomanno, Laura Lea Rubino, Christopher Costello"
date: "`r format(Sys.time(), '%B %d, %Y')`"
fontsize: 11pt
bibliography: "../pew-subsidies.bib"
---

# Introduction 

This script generates the most ambitious global and regional results obtained by removing all capacity enhancing subsidies from all WTO Members and Observers.

```{r setup, include=FALSE}
# Load packages
library(knitr) 
library(tidyverse)
library(countrycode)

knitr::opts_chunk$set(echo = TRUE)

make_plots <- T

if(make_plots){
  library(RColorBrewer)
  library(scales)
}

bad_subsidy_types <- c("B1", "B2", "B3", "B4", "B5", "B6", "B7")
ugly_subsidy_types <- c("C1", "C2", "C3")
good_subsidy_types <- c("A1", "A2", "A3")

subsidy_types_sorted_sumaila <- c(good_subsidy_types, bad_subsidy_types, ugly_subsidy_types)

# Threshold to be considered managed (using FMI scores)
managed_cutoff <- 0.75

end_year <- 2080

# Directories for the output files generated by this script
results_dir <- paste0(here::here("results", "07-proposals/"), "mgmt_threshold_", managed_cutoff, "/")
if (dir.exists(results_dir) == F) {
  dir.create(results_dir, recursive = T)
}
```

```{r}
# Source model script
source(here::here("app", "scripts", "BioEconModel.R"))

# Source create fleets script
source(here::here("app", "scripts", "CreateFleets.R"))

# Source plotting script
source(here::here("scripts", "functions", "BioEconomicModelPlots.R"))
```

```{r}
# Load country dependencies helper file
country_dependencies <- read_csv(here::here("app", "data", "country_dependencies.csv")) %>%
   mutate(display_name = case_when(!is.na(WTO_name) ~ WTO_name,
                                  iso3 == "ANT" ~ "Netherlands Antilles",
                                  iso3 == "ASC" ~ "Ascension Island", 
                                  iso3 == "CPT" ~ "Clipperton Island",
                                  iso3 == "TAA" ~ "Tristan da Cunha",
                                  TRUE ~ countrycode(iso3, "iso3c", "country.name"))) %>%
  arrange(sovereign_iso3) 

# Vector of all WTO Members and Observers for use in the app [does not include the overseas territories associated with them]
wto_members_and_observers <- country_dependencies$iso3[country_dependencies$is_WTO & !country_dependencies$is_overseas_territory]
```

```{r}
# Load vessel list
vessel_dat <- read.csv(here::here("app", "data", "vessel_list_2018_final.csv"), stringsAsFactors = F) %>%
  left_join(country_dependencies %>% dplyr::select(iso3, is_WTO), by = c("flag_iso3" = "iso3"))

rel <- read_csv(here::here("data", "lookup-tables", "oecd_relative_effects_lookup_table.csv"))

vessel_dat <- vessel_dat %>%
   mutate(B1_subs = B1_subs * rel$rel_effect_effort[rel$type == "B1"], 
           B2_subs = B2_subs * rel$rel_effect_effort[rel$type == "B2"],
           B3_subs = B3_subs * rel$rel_effect_effort[rel$type == "B3"],
           B4_subs = B4_subs * rel$rel_effect_effort[rel$type == "B4"],
           B5_subs = B5_subs * rel$rel_effect_effort[rel$type == "B5"], 
           B6_subs = B6_subs * rel$rel_effect_effort[rel$type == "B6"],
           B7_subs = B7_subs * rel$rel_effect_effort[rel$type == "B7"], 
           C1_subs = C1_subs * rel$rel_effect_effort[rel$type == "C1"], 
           C2_subs = C2_subs * rel$rel_effect_effort[rel$type == "C2"],
           C3_subs = C3_subs * rel$rel_effect_effort[rel$type == "C3"]) %>%
  ungroup() %>%
  mutate(bad_subs = rowSums(select(., one_of(paste0(bad_subsidy_types, "_subs")))),
         ugly_subs = rowSums(select(., one_of(paste0(ugly_subsidy_types, "_subs")))),
         good_subs = rowSums(select(., one_of(paste0(good_subsidy_types, "_subs")))),
         bad_ugly_subs = rowSums(select(., one_of(paste0(c(bad_subsidy_types, ugly_subsidy_types), "_subs")))))

# Create high seas code
vessel_dat <- vessel_dat %>%
  mutate(eez_hs_code = case_when(eez_id == 0 ~ paste0("HS-", fao_region),
                                 TRUE ~ as.character(eez_id)))
```

```{r}
# Load biological parameters for the model
bio_dat_regional <- read.csv(here::here("app", "data", "model_parameters_regional_3_regions.csv"))

# Regional parameter list
bio_dat_regional_list <- bio_dat_regional %>%
  gather(region, value, -c(1:2)) %>%
  group_by(region) %>%
  group_split()
```

```{r}
# Proposal settings
proposal_settings <- read.csv(here::here("app", "data", "wto_proposal_settings.csv"), stringsAsFactors = F)

# Proposal names
included_proposals <- proposal_settings %>%
  dplyr::filter(include == "Yes") %>%
  mutate(display_name = case_when(proposal == "Default" ~ "None",
                                  TRUE ~ paste0(title_tool, " (", proposal, ")"))) %>%
  dplyr::select(category, proposal, display_name) %>%
  arrange(category)

proposal_choices <- included_proposals$proposal
names(proposal_choices) <- included_proposals$display_name
```

```{r}
# 1) Cap/tier lookup table
cap_tier_lookup_table <- read_csv(here::here("app","data","cap_tier_lookup_table.csv"))

```

## Model proposals

```{r}
proposal_results <- NULL

for(i in 2:length(proposal_choices)){
  
  # Choose proposal
  proposal_name <- proposal_choices[i]
  
  print(proposal_name)
  
  # Get all data for that proposal
  selected_proposal <- proposal_settings %>%
      dplyr::filter(proposal == proposal_name)
  
  # Get all IUU conditions
  iuu <- 
    list("definitions" = unlist(str_split(selected_proposal$iuu_definitions, ", ")),
         "assumption" = selected_proposal$iuu_assumption,
         "percent" = selected_proposal$iuu_percent,
         "scope" = selected_proposal$iuu_scope,
         "scope_select" = unlist(str_split(selected_proposal$iuu_scope_select, ", ")),
         "scope_manual" = unlist(str_split(selected_proposal$iuu_scope_manual, ", ")),
         "allow_sdt" = selected_proposal$iuu_allow_sdt,
         "sdt_ldc" = selected_proposal$iuu_sdt_ldc,
         "sdt_what_ldc" = unlist(str_split(selected_proposal$iuu_sdt_what_ldc, ", ")),
         "sdt_time_delay_ldc" = selected_proposal$iuu_sdt_time_delay_ldc,
         "sdt_developing" = selected_proposal$iuu_sdt_developing,
         "sdt_what_developing" = unlist(str_split(selected_proposal$iuu_sdt_what_developing, ", ")),
         "sdt_time_delay_developing" = selected_proposal$iuu_sdt_time_delay_developing,
         "sdt_sve" = selected_proposal$iuu_sdt_sve,
         "sdt_what_sve" = unlist(str_split(selected_proposal$iuu_sdt_what_sve, ", ")),
         "sdt_time_delay_sve" = selected_proposal$iuu_sdt_time_delay_sve)
  
   # Get all OA conditions
   oa <- 
     list("definitions" = unlist(str_split(selected_proposal$oa_definitions, ", ")),
          "scope" = selected_proposal$oa_scope,
          "scope_select" = unlist(str_split(selected_proposal$oa_scope_select, ", ")),
          "scope_manual" = unlist(str_split(selected_proposal$oa_scope_manual, ", ")),
          "hs_cutoff" = selected_proposal$oa_hs_cutoff,
          "length_cutoff" = selected_proposal$oa_length_cutoff,
          "tonnage_cutoff" = selected_proposal$oa_tonnage_cutoff,
          "engine_cutoff" = selected_proposal$oa_engine_cutoff,
          "allow_sdt" = selected_proposal$oa_allow_sdt,
          "sdt_ldc" = selected_proposal$oa_sdt_ldc,
          "sdt_what_ldc" = unlist(str_split(selected_proposal$oa_sdt_what_ldc, ", ")),
          "sdt_hs_cutoff_ldc" = selected_proposal$oa_sdt_hs_cutoff_ldc,
          "sdt_time_delay_ldc" = selected_proposal$oa_sdt_time_delay_ldc,
          "sdt_developing" = selected_proposal$oa_sdt_developing,
          "sdt_what_developing" = unlist(str_split(selected_proposal$oa_sdt_what_developing, ", ")),
          "sdt_hs_cutoff_developing" = selected_proposal$oa_sdt_hs_cutoff_developing,
          "sdt_time_delay_developing" = selected_proposal$oa_sdt_time_delay_developing,
          "sdt_sve" = selected_proposal$oa_sdt_sve,
          "sdt_what_sve" = unlist(str_split(selected_proposal$oa_sdt_what_sve, ", ")),
          "sdt_hs_cutoff_sve" = selected_proposal$oa_sdt_hs_cutoff_sve,
          "sdt_time_delay_sve" = selected_proposal$oa_sdt_time_delay_sve)
   
   # Get all Overcap conditions
   overcap <- 
     list("definitions" = unlist(str_split(selected_proposal$overcap_definitions, ", ")),
          "scope" = selected_proposal$overcap_scope,
          "scope_select" = unlist(str_split(selected_proposal$overcap_scope_select, ", ")),
          "scope_manual" = unlist(str_split(selected_proposal$overcap_scope_manual, ", ")),
          "hs_cutoff" = selected_proposal$overcap_hs_cutoff,
          "length_cutoff" = selected_proposal$overcap_length_cutoff,
          "tonnage_cutoff" = selected_proposal$overcap_tonnage_cutoff,
          "engine_cutoff" = selected_proposal$overcap_engine_cutoff,
          "allow_sdt" = selected_proposal$overcap_allow_sdt,
          "sdt_ldc" = selected_proposal$overcap_sdt_ldc,
          "sdt_what_ldc" = unlist(str_split(selected_proposal$overcap_sdt_what_ldc, ", ")),
          "sdt_hs_cutoff_ldc" = selected_proposal$overcap_sdt_hs_cutoff_ldc,
          "sdt_time_delay_ldc" = selected_proposal$overcap_sdt_time_delay_ldc,
          "sdt_developing" = selected_proposal$overcap_sdt_developing,
          "sdt_what_developing" = unlist(str_split(selected_proposal$overcap_sdt_what_developing, ", ")),
          "sdt_hs_cutoff_developing" = selected_proposal$overcap_sdt_hs_cutoff_developing,
          "sdt_time_delay_developing" = selected_proposal$overcap_sdt_time_delay_developing,
          "sdt_sve" = selected_proposal$overcap_sdt_sve,
          "sdt_what_sve" = unlist(str_split(selected_proposal$overcap_sdt_what_sve, ", ")),
          "sdt_hs_cutoff_sve" = selected_proposal$overcap_sdt_hs_cutoff_sve,
          "sdt_time_delay_sve" = selected_proposal$overcap_sdt_time_delay_sve)
   
   # Get all Cap/Tier conditions
   cap_tier = 
     list("on_off" = selected_proposal$cap_on_off,
          "subsidy_types" = unlist(str_split(selected_proposal$cap_subsidy_types, ", ")),
          "tier_number" = selected_proposal$cap_tier_number,
          "tier_system" = selected_proposal$tier_system,
          "two_tier_cutoff" = selected_proposal$two_tier_cutoff,
          "three_tier_cutoff" = as.numeric(unlist(str_split(selected_proposal$three_tier_cutoff, ", "))),
          "tier1_cap_rule" = selected_proposal$tier1_cap_rule,
          "tier2_cap_rule" = selected_proposal$tier2_cap_rule,
          "tier3_cap_rule" = selected_proposal$tier3_cap_rule,
          "tier1_cap_value" = selected_proposal$tier1_cap_value,
          "tier1_cap_percent" = selected_proposal$tier1_cap_percent,
          "tier1_cap_best_percent_subs" = selected_proposal$tier1_cap_best_percent_subs,
          "tier1_cap_best_percent_landed_value" = selected_proposal$tier1_cap_best_percent_landed_value,
          "tier1_cap_best_percent_fishers" = selected_proposal$tier1_cap_best_percent_fishers,
          "tier2_cap_value" = selected_proposal$tier2_cap_value,
          "tier2_cap_percent" = selected_proposal$tier2_cap_percent,
          "tier2_cap_best_percent_subs" = selected_proposal$tier2_cap_best_percent_subs,
          "tier2_cap_best_percent_landed_value" = selected_proposal$tier2_cap_best_percent_landed_value,
          "tier2_cap_best_percent_fishers" = selected_proposal$tier2_cap_best_percent_fishers,
          "tier3_cap_value" = selected_proposal$tier3_cap_value,
          "tier3_cap_percent" = selected_proposal$tier3_cap_percent,
          "tier3_cap_best_percent_subs" = selected_proposal$tier3_cap_best_percent_subs,
          "tier3_cap_best_percent_landed_value" = selected_proposal$tier3_cap_best_percent_landed_value,
          "tier3_cap_best_percent_fishers" = selected_proposal$tier3_cap_best_percent_fishers)
   
   ### Find fleets
    fleet <-  CreateFleets(
      vessel_list = vessel_dat,
      iuu = iuu,
      oa = oa,
      overcap = overcap,
      cap_tier = cap_tier,
      managed_threshold = managed_cutoff,
      subsidy_types_all = subsidy_types_sorted_sumaila,
      cap_tier_lookup = cap_tier_lookup_table,
      country_lookup = country_dependencies)
    
    # Make list
    fleet_list <- fleet$summary %>%
      group_by(region) %>%
      group_split()
    names(fleet_list) <- colnames(bio_dat_regional)[-c(1:2)]
    
    # Run model
    results <- pmap_df(list(fleet = fleet_list,
                                   region = names(fleet_list),
                                   bio_param = bio_dat_regional_list),
                                  BioEconModel,
                                  end_year = end_year,
                                  return = "all")

    # Extract results timeseries
    results_all <- results %>%
      dplyr::filter(Year > 2018) %>%
      group_by(Year, Variable, Fleet) %>%
      mutate(Diff = case_when(BAU != 0 ~ (Reform - BAU) / abs(BAU),
      TRUE ~ 0)) %>%
      ungroup() %>%
      mutate(run_id = proposal_name,
             run_name = names(proposal_name),
             run_group = unique(proposal_settings$category[proposal_settings$proposal == proposal_name]))
    
      write_csv(results_all, paste0(results_dir, str_replace_all(names(proposal_name), "/", "_"), ".csv"))
    
    # Add to data frame
      proposal_results <- proposal_results %>%
        bind_rows(results_all)
  
}
```

Make plots with all proposals and the most ambitious result

```{r}
# Load most ambitous results from previous script
most_ambitious_results <- read_csv(paste0(here::here("results", "06-run-model/"), "mgmt_threshold_", managed_cutoff, "/", "BC_rel_ts_data.csv")) %>%
  mutate(run_id = "Ambitious Reform",
         run_group = "Ambitious Reform")

plot_results <- proposal_results %>%
  dplyr::filter(run_id != "RD/TN/RL/103") %>%
  bind_rows(most_ambitious_results)

# Make plots
if(make_plots){
  
  # 1) global (aggregated) timeseries plot
  compare_ts_plot <- BioEconomicModelPlots(dat = plot_results,
                                           spatial_res = "global",
                                           temporal_res = "all",
                                           start_year = 2018,
                                           end_year = end_year,
                                           plot_name = "all_proposals_ts_plot",
                                           plot_width = 8,
                                           plot_height = 10,
                                           results_dir = results_dir,
                                           group_var = "run_id",
                                           color_var = "run_group",
                                           legend_pos_manual = "bottom",
                                           legend_name = "Scenario Type")
  
  # 2) global (aggregated) "kobe" final year plot
  compare_end_plot <- BioEconomicModelPlots(dat = plot_results,
                                            spatial_res = "global",
                                            temporal_res = "last",
                                            end_year = end_year,
                                            plot_name = "all_proposals_end_plot",
                                            plot_width = 8,
                                            plot_height = 8,
                                            results_dir = results_dir,
                                            group_var = "run_id",
                                            color_var = "run_group",
                                            legend_pos_manual = "bottom",
                                            legend_name = "Scenario Type")
  
  # 3) regional timeseries plot
  regional_compare_ts_plot <- BioEconomicModelPlots(dat = plot_results,
                                                    spatial_res = "regional",
                                                    temporal_res = "all",
                                                    start_year = 2018,
                                                    end_year = end_year,
                                                    plot_name = "regional_all_proposals_ts_plot",
                                                    plot_width = 12,
                                                    plot_height = 10,
                                                    results_dir = results_dir,
                                                    group_var = "run_id",
                                                    color_var = "run_group",
                                                    legend_pos_manual = "bottom",
                                                    legend_name = "Scenario Type")
  
  # 4) regional "kobe" final year plot
  regional_compare_end_plot <- BioEconomicModelPlots(dat = plot_results,
                                                     spatial_res = "regional",
                                                     temporal_res = "last",
                                                     end_year = end_year,
                                                     plot_name = "regional_all_proposals_end_plot",
                                                     plot_width = 12,
                                                     plot_height = 8,
                                                     results_dir = results_dir,
                                                     group_var = "run_id",
                                                     color_var = "run_group",
                                                     legend_pos_manual = "bottom",
                                                     legend_name = "Scenario Type")
}
```

## Extract 2060 and end year results for all proposals and save as nice tables

```{r}
all_results_global_output_table <- plot_results %>%
  dplyr::filter(Year %in% c(2060, end_year)) %>%
  dplyr::filter(Variable %in% c("biomass", "catches_total", "revenue_total", "u_mort_total")) %>%
  group_by(Year, Variable, Fleet, run_id, run_name, run_group) %>%
  summarize(BAU_tot = sum(BAU, na.rm = T),
            Reform_tot = sum(Reform, na.rm = T),
            Diff_tot = case_when(BAU_tot != 0 ~ (Reform_tot - BAU_tot)/abs(BAU_tot),
                            TRUE ~ 0)) %>%
  ungroup() %>%
  mutate(Variable = case_when(Variable == "biomass" ~ "Biomass",
                                Variable == "catches_total" ~ "Catches",
                                Variable == "revenue_total" ~ "Revenue",
                                Variable == "u_mort_total" ~ "Fishing Mortality")) %>%
  dplyr::select(Id = run_id,
                Name = run_name,
                Category = run_group, 
                Year,
                Diff_tot,
                Variable) %>%
  spread(Variable, Diff_tot)

write.csv(all_results_global_output_table, paste0(results_dir, "all_results_global_output_table.csv"))

# Get rounded end values
global_biomass_2060 <- round(all_results_global_output_table$Biomass[all_results_global_output_table$Year == 2060 & all_results_global_output_table$Id == "Ambitious Reform"]*100, 2)
global_biomass_end <- round(all_results_global_output_table$Biomass[all_results_global_output_table$Year == end_year & all_results_global_output_table$Id == "Ambitious Reform"]*100, 2)

global_catches_2060 <- round(all_results_global_output_table$Catches[all_results_global_output_table$Year == 2060 & all_results_global_output_table$Id == "Ambitious Reform"]*100, 2)
global_catches_end <- round(all_results_global_output_table$Catches[all_results_global_output_table$Year == end_year & all_results_global_output_table$Id == "Ambitious Reform"]*100, 2)

# Now do regional
all_results_regional_output_table <- plot_results %>%
  dplyr::filter(Year %in% c(2060, end_year)) %>%
  dplyr::filter(Variable %in% c("biomass", "catches_total", "revenue_total", "u_mort_total")) %>%
  mutate(Variable = case_when(Variable == "biomass" ~ "Biomass",
                                Variable == "catches_total" ~ "Catches",
                                Variable == "revenue_total" ~ "Revenue",
                                Variable == "u_mort_total" ~ "Fishing Mortality")) %>%
  dplyr::select(Id = run_id,
                Name = run_name,
                Category = run_group, 
                Year,
                Region,
                Diff,
                Variable) %>%
  spread(Variable, Diff)
  
write.csv(all_results_regional_output_table, paste0(results_dir, "all_results_regional_output_table.csv"))
```

## Do the same with aboslute values

```{r}
# Weight of a mature dairy cow in mt
cow_weight <- 0.6803886

all_results_global_cow_equivalent_table <- plot_results %>%
  dplyr::filter(Year %in% c(2060, end_year)) %>%
  dplyr::filter(Variable %in% c("biomass", "catches_total")) %>%
  group_by(Year, Variable, Fleet, run_id, run_name, run_group) %>%
  summarize(BAU_tot = sum(BAU, na.rm = T),
            Reform_tot = sum(Reform, na.rm = T),
            abs_Diff_tot = case_when(BAU_tot != 0 ~ Reform_tot-BAU_tot,
                                     TRUE ~ 0),
            cow_Diff = abs_Diff_tot*cow_weight) %>%
  ungroup() %>%
  mutate(Variable = case_when(Variable == "biomass" ~ "Biomass",
                              Variable == "catches_total" ~ "Catches")) %>%
  dplyr::select(Id = run_id,
                Name = run_name,
                Category = run_group, 
                Year,
                cow_Diff,
                Variable) %>%
  spread(Variable, cow_Diff)

write.csv(all_results_global_cow_equivalent_table, paste0(results_dir, "all_results_global_cow_equivalent_table.csv"))

all_results_regional_cow_equivalent_table <- plot_results %>%
  dplyr::filter(Year %in% c(2060, end_year)) %>%
  dplyr::filter(Variable %in% c("biomass", "catches_total")) %>%
  mutate(Variable = case_when(Variable == "biomass" ~ "Biomass",
                                Variable == "catches_total" ~ "Catches")) %>%
  mutate(abs_Diff = case_when(BAU != 0 ~ Reform-BAU,
                              TRUE ~ 0),
         cow_Diff = abs_Diff*cow_weight) %>%
  dplyr::select(Id = run_id,
                Name = run_name,
                Category = run_group, 
                Year,
                Region,
                cow_Diff,
                Variable) %>%
  spread(Variable, cow_Diff)

write.csv(all_results_regional_cow_equivalent_table, paste0(results_dir, "all_results_regional_cow_equivalent_table.csv"))

```

