---
output:
  html_document: default

title: "SubsidyExplorer - Step 7: Sensitivity Analysis"
author: "Kat Millage, Vienna Saccomanno, Laura Lea Rubino, Christopher Costello"
date: "`r format(Sys.time(), '%B %d, %Y')`"
fontsize: 11pt
bibliography: "../pew-subsidies.bib"
---

```{r setup, include=FALSE}
# Load packages
library(knitr) 
library(tidyverse)

knitr::opts_chunk$set(echo = TRUE)

make_plots <- T

if(make_plots){
  library(RColorBrewer)
  library(scales)
}

# Directories for the output files generated by this script
results_dir <- here::here("results", "07-sensitivity-analysis/")
if (dir.exists(results_dir) == F) {
  dir.create(results_dir, recursive = T)
}
```

```{r}
# Load vessel list
vessel_dat <- read.csv(here::here("app", "data", "vessel_list_2018_final.csv"), stringsAsFactors = F)

# Create high seas code
vessel_dat <- vessel_dat %>%
  mutate(eez_hs_code = case_when(eez_id == 0 ~ paste0("HS-", fao_region),
                                 TRUE ~ as.character(eez_id)))

# Load country dependencies helper file
country_dependencies <- read_csv(here::here("data", "lookup-tables", "country_dependencies.csv"))
```


## Relative subsidy effects

```{r}
# Vessel list with "effective" subsidies
### Not applicable currently - old experimentation with pro-rating the dollar value of different subsidies
# if(pro_rate_subsidies == T){
# 
#   vessel_dat <- vessel_dat %>%
#     mutate(B1_subs = B1_subs * 0.54, # boat construction/renovation - matched to payments based on vessels
#            B2_subs = B2_subs * 1, # fishery development projects/support services - matched to payments based on variable use
#            B3_subs = B3_subs * 0.87, # port construction and renovation - matched to payments based on vessels
#            B4_subs = B4_subs * 0.87, # price/marketing support, processing infrastructure - matched to payments based on output
#            B5_subs = B5_subs * 0.76, # non-fuel tax exemptions - matched to payments based on fishers income
#            B6_subs = B6_subs * 0.56, # foreign access agreements - matched to payments based on fishers own capital
#            B7_subs = B7_subs * 0.84, # fuel - matched to payments based on fuel use
#            bad_subs = (B1_subs + B2_subs + B3_subs + B4_subs + B5_subs + B6_subs + B7_subs))
# 
# }
```

## Bioeconomic model parameters

